# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ca6dab71bac70de136c6bda26d17ca10d30f7a85f5d852799c233274b1512d42afaaeb55ade1f606a3510b83885f04c76a2680e627db206d3fa967944dcf833

test:
  secret_key_base: 4394638289d8eaedb9769c3d57834cda5d793fc7a6d98666a81d73e249800442ed54f6348fbb20070dbb76a9e877e5f8336b21edf925088649507373da250346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
